### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by SrikanthTati** [Landoop/fast-avro-write#1]
I'm trying to use this lib in a Scala 2.12 project and got this error

> Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
> 	at com.landoop.avro.FastDataFileWriterBuilder.<init>(FastDataFileWriterBuilder.scala:28)
> 	at com.landoop.avro.FastDataFileWriterBuilder.<init>(FastDataFileWriterBuilder.scala:46)
> 	at com.landoop.avro.FastDataFileWriterBuilder$.apply(FastDataFileWriterBuilder.scala:180)

It probably is because this library is built only for Scala 2.11. `scala = '2.11.8'`
https://github.com/Landoop/fast-avro-write/blob/master/build.gradle#L55

I'm not familiar with Gradle. Is there a way/need to build Scala 2.12 version for this?

**Comment by stheppi** [comment]
We will look to provide a scala 2.12 release
